add Timer
MateuszBlach/GPU_SR0910_sito_Eratostenesa pull request #1
Opened 2024-10-26 07:50 UTC by MateuszBlach

shared timer that can be used in GPU/CPU algorithm to measure the time

2024-10-26 15:46 UTC, Jocho14 commented on shared/timer/Timer.cpp
> +#include "Timer.h"
adjust import

2024-10-26 17:05 UTC, Jocho14 commented on shared/timer/Timer.cpp
> +#include "Timer.h"
change to .hpp file

2024-10-26 17:06 UTC, Jocho14 commented on shared/timer/Timer.cpp
> +void Timer::resetTime() {
rename to Timer::reset()
```suggestion
void Timer::reset() {
```

2024-10-26 17:08 UTC, Jocho14 commented on shared/timer/Timer.h
> +#ifndef TIMER_H
```suggestion
#ifndef TIMER_HPP
```

2024-10-26 17:09 UTC, Jocho14 commented on shared/timer/Timer.h
> +#ifndef TIMER_H
rename to TIMER_HPP

2024-10-26 17:09 UTC, Jocho14 commented on shared/timer/Timer.h
> +#define TIMER_H
rename to TIMER_HPP

2024-10-26 17:25 UTC, Jocho14 commented on shared/timer/Timer.h
> +#endif
Add corresponding ifndef as a comment - #endif  // TIMER_HPP

2024-10-26 17:25 UTC, Jocho14 commented on shared/timer/Timer.h
> +#endif
leave a blank line at the end of the file

2024-10-26 17:35 UTC, Jocho14 commented on shared/timer/Timer.cpp
> +Timer::Timer() : running(false) {}
initialize startTime and endTime using default initializer:
startTime(), endTime()

2024-10-26 17:38 UTC, Jocho14 requested changes
Please address the comments

2024-10-26 17:50 UTC, MateuszBlach commented
check now @Jocho14

2024-10-26 18:06 UTC, Jocho14 commented on shared/timer/Timer.hpp
>      std::chrono::time_point<std::chrono::high_resolution_clock> startTime;
add underscore suffix "_" in every private member variable. For example:
`std::chrono::time_point<std::chrono::high_resolution_clock> start_time_;`

2024-10-26 18:07 UTC, Jocho14 requested changes
Please resolve the rest of the comments

2024-10-26 18:15 UTC, MateuszBlach commented
check now @Jocho14

2024-10-27 12:47 UTC, MateuszBlach commented
@Jocho14 check now

2024-10-27 12:51 UTC, Jocho14 commented
+2

2024-10-27 12:52 UTC, merged